In [1]:
import python.utils as utils
import python.plots as plots
import importlib

importlib.reload(utils)

X_raw = utils.fetch_dataset_web_traffic('wide')

x:\Egyetem\semester_six\forecast_research\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
X_raw

,2NE1_zh.wikipedia.org_all-access_spider,2PM_zh.wikipedia.org_all-access_spider,3C_zh.wikipedia.org_all-access_spider,4minute_zh.wikipedia.org_all-access_spider,52_Hz_I_Love_You_zh.wikipedia.org_all-access_spider,5566_zh.wikipedia.org_all-access_spider,91Days_zh.wikipedia.org_all-access_spider,A'N'D_zh.wikipedia.org_all-access_spider,AKB48_zh.wikipedia.org_all-access_spider,ASCII_zh.wikipedia.org_all-access_spider,...,Drake_(músico)_es.wikipedia.org_all-access_spider,Skam_(serie_de_televisión)_es.wikipedia.org_all-access_spider,Legión_(serie_de_televisión)_es.wikipedia.org_all-access_spider,Doble_tentación_es.wikipedia.org_all-access_spider,Mi_adorable_maldición_es.wikipedia.org_all-access_spider,Underworld_(serie_de_películas)_es.wikipedia.org_all-access_spider,Resident_Evil:_Capítulo_Final_es.wikipedia.org_all-access_spider,Enamorándome_de_Ramón_es.wikipedia.org_all-access_spider,Hasta_el_último_hombre_es.wikipedia.org_all-access_spider,Francisco_el_matemático_(serie_de_televisión_de_2017)_es.wikipedia.org_all-access_spider
ds,,,,,,,,,,,,,,,,,,,,,
2015-07-01,18.0,11.0,1.0,35.0,NaN,12.0,NaN,118.0,5.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-07-02,11.0,14.0,0.0,13.0,NaN,7.0,NaN,26.0,23.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-07-03,5.0,15.0,1.0,10.0,NaN,4.0,NaN,30.0,14.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-07-04,13.0,18.0,1.0,94.0,NaN,5.0,NaN,24.0,12.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2015-07-05,14.0,11.0,0.0,4.0,NaN,20.0,NaN,29.0,9.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-09-06,27.0,25.0,7.0,16.0,23.0,20.0,10.0,44.0,44.0,32.0,...,2.0,4.0,5.0,19.0,8.0,2.0,5.0,13.0,8.0,2.0
2017-09-07,29.0,26.0,3.0,19.0,28.0,18.0,8.0,25.0,33.0,34.0,...,0.0,8.0,3.0,7.0,7.0,4.0,5.0,9.0,2.0,7.0
2017-09-08,23.0,23.0,4.0,30.0,14.0,17.0,5.0,39.0,52.0,29.0,...,5.0,7.0,4.0,14.0,9.0,4.0,2.0,21.0,4.0,6.0
2017-09-09,54.0,13.0,7.0,38.0,8.0,14.0,3.0,25.0,21.0,23.0,...,7.0,7.0,3.0,12.0,11.0,8.0,2.0,16.0,3.0,10.0
2017-09-10,38.0,81.0,6.0,4.0,7.0,11.0,5.0,50.0,48.0,25.0,...,1.0,19.0,3.0,8.0,5.0,2.0,4.0,6.0,3.0,3.0

In [3]:
import importlib

importlib.reload(utils)

X = utils.reduce_dataset(X_raw, 100)
X = utils.filter_last_days_available(X, 28*2 + 7)
X = utils.align_fill_and_trim_series(X)

plots.plot_heatmap(X)

In [6]:
import python.temporal_hierarchy

importlib.reload(python.temporal_hierarchy)

In [8]:
from python.temporal_hierarchy import TemporalHierarchy
from python.aggregation import WEEKENDS, WEEKDAYS, WEEKS, FORTNIGHTS, MONTHS, DAYS
import importlib

importlib.reload(plots)

th = TemporalHierarchy([
    DAYS, WEEKENDS, WEEKDAYS, WEEKS, FORTNIGHTS, MONTHS
])

summ = th.make_summing_matrix()

plots.plot_summing_matrix(summ)

In [9]:
X.tail(10)

,2NE1_zh.wikipedia.org_all-access_spider,2PM_zh.wikipedia.org_all-access_spider,3C_zh.wikipedia.org_all-access_spider,4minute_zh.wikipedia.org_all-access_spider,52_Hz_I_Love_You_zh.wikipedia.org_all-access_spider,5566_zh.wikipedia.org_all-access_spider,91Days_zh.wikipedia.org_all-access_spider,A'N'D_zh.wikipedia.org_all-access_spider,AKB48_zh.wikipedia.org_all-access_spider,ASCII_zh.wikipedia.org_all-access_spider,...,Lovelyz_zh.wikipedia.org_all-access_spider,Lulu_zh.wikipedia.org_all-access_spider,MADTOWN_zh.wikipedia.org_all-access_spider,MAMAMOO_zh.wikipedia.org_all-access_spider,MONSTA_X_zh.wikipedia.org_all-access_spider,Madame_Antoine_zh.wikipedia.org_all-access_spider,Mamamoo_zh.wikipedia.org_all-access_spider,Mike_D._Angelo_zh.wikipedia.org_all-access_spider,Miss_A_zh.wikipedia.org_all-access_spider,Missing9_zh.wikipedia.org_all-access_spider
ds,,,,,,,,,,,,,,,,,,,,,
2017-09-01,19.0,32.0,6.0,7.0,16.0,13.0,12.0,74.0,53.0,20.0,...,68.0,5.0,9.0,9.0,8.0,4.0,20.0,16.0,23.0,13.0
2017-09-02,33.0,30.0,6.0,19.0,16.0,13.0,8.0,39.0,107.0,16.0,...,16.0,4.0,5.0,19.0,13.0,4.0,11.0,24.0,17.0,14.0
2017-09-03,33.0,11.0,7.0,19.0,19.0,45.0,5.0,11.0,63.0,22.0,...,15.0,5.0,2.0,17.0,8.0,6.0,13.0,20.0,18.0,10.0
2017-09-04,18.0,19.0,2.0,9.0,9.0,4.0,7.0,55.0,42.0,19.0,...,46.0,2.0,6.0,19.0,5.0,2.0,17.0,17.0,24.0,9.0
2017-09-05,16.0,54.0,4.0,6.0,20.0,13.0,8.0,71.0,24.0,21.0,...,36.0,4.0,5.0,8.0,23.0,1.0,15.0,14.0,22.0,9.0
2017-09-06,27.0,25.0,7.0,16.0,23.0,20.0,10.0,44.0,44.0,32.0,...,16.0,5.0,5.0,4.0,17.0,5.0,30.0,13.0,10.0,16.0
2017-09-07,29.0,26.0,3.0,19.0,28.0,18.0,8.0,25.0,33.0,34.0,...,55.0,32.0,9.0,10.0,26.0,13.0,22.0,11.0,16.0,14.0
2017-09-08,23.0,23.0,4.0,30.0,14.0,17.0,5.0,39.0,52.0,29.0,...,12.0,6.0,7.0,10.0,16.0,5.0,14.0,8.0,11.0,9.0
2017-09-09,54.0,13.0,7.0,38.0,8.0,14.0,3.0,25.0,21.0,23.0,...,10.0,6.0,10.0,10.0,17.0,8.0,22.0,18.0,18.0,8.0
2017-09-10,38.0,81.0,6.0,4.0,7.0,11.0,5.0,50.0,48.0,25.0,...,24.0,3.0,3.0,11.0,7.0,3.0,13.0,7.0,8.0,20.0

In [10]:
from python.aggregation import WEEKS, WEEKENDS, WEEKDAYS, FORTNIGHTS, DAYS, MONTHS
from python.temporal_hierarchy import  ForecastLevel
import python.temporal_hierarchy

importlib.reload(python.temporal_hierarchy)

fl = ForecastLevel(WEEKS)
fl.prepare_aggregation(X)
fl.make_forecast(28*2)

In [11]:
fl.base_forecasts

,2NE1_zh.wikipedia.org_all-access_spider,2PM_zh.wikipedia.org_all-access_spider,3C_zh.wikipedia.org_all-access_spider,4minute_zh.wikipedia.org_all-access_spider,52_Hz_I_Love_You_zh.wikipedia.org_all-access_spider,5566_zh.wikipedia.org_all-access_spider,91Days_zh.wikipedia.org_all-access_spider,A'N'D_zh.wikipedia.org_all-access_spider,AKB48_zh.wikipedia.org_all-access_spider,ASCII_zh.wikipedia.org_all-access_spider,...,Lovelyz_zh.wikipedia.org_all-access_spider,Lulu_zh.wikipedia.org_all-access_spider,MADTOWN_zh.wikipedia.org_all-access_spider,MAMAMOO_zh.wikipedia.org_all-access_spider,MONSTA_X_zh.wikipedia.org_all-access_spider,Madame_Antoine_zh.wikipedia.org_all-access_spider,Mamamoo_zh.wikipedia.org_all-access_spider,Mike_D._Angelo_zh.wikipedia.org_all-access_spider,Miss_A_zh.wikipedia.org_all-access_spider,Missing9_zh.wikipedia.org_all-access_spider
ds,,,,,,,,,,,,,,,,,,,,,
2017-07-23,156.857773,218.258911,22.929995,141.433304,89.021095,149.916977,40.618496,175.901901,353.431458,191.096268,...,276.24173,20.27766,54.823589,94.760368,193.389114,30.302389,375.072662,62.537338,113.80294,78.999397
2017-07-30,157.756287,225.940002,21.978334,133.776932,89.021095,149.916977,40.288376,175.901901,353.160614,191.096268,...,276.24173,20.27766,54.823589,95.883194,191.486237,30.915026,375.072662,62.537338,113.80294,78.999397
2017-08-06,158.636017,232.281052,21.026674,126.573174,89.021095,149.916977,39.982773,175.901901,352.906555,191.096268,...,276.24173,20.27766,54.823589,97.006020,189.583359,31.449591,375.072662,62.537338,113.80294,78.999397
2017-08-13,159.497375,237.515823,20.075014,119.795273,89.021095,149.916977,39.699871,175.901901,352.668243,191.096268,...,276.24173,20.27766,54.823589,98.128853,187.680481,31.916033,375.072662,62.537338,113.80294,78.999397
2017-08-20,160.340729,241.837326,19.123354,113.418053,89.021095,149.916977,39.437984,175.901901,352.444733,191.096268,...,276.24173,20.27766,54.823589,99.251678,185.777603,32.323032,375.072662,62.537338,113.80294,78.999397
2017-08-27,161.166458,245.404892,18.171694,107.417831,89.021095,149.916977,39.195545,175.901901,352.235107,191.096268,...,276.24173,20.27766,54.823589,100.374512,183.874741,32.678165,375.072662,62.537338,113.80294,78.999397
2017-09-03,161.974930,248.350067,17.220034,101.772316,89.021095,149.916977,38.971115,175.901901,352.038483,191.096268,...,276.24173,20.27766,54.823589,101.497337,181.971863,32.988045,375.072662,62.537338,113.80294,78.999397
2017-09-10,162.766495,250.781403,16.268373,96.460541,89.021095,149.916977,38.763351,175.901901,351.854065,191.096268,...,276.24173,20.27766,54.823589,102.620163,180.068985,33.258430,375.072662,62.537338,113.80294,78.999397

In [41]:
importlib.reload(python.temporal_hierarchy)

from python.aggregation import WEEKS, WEEKENDS, WEEKDAYS, FORTNIGHTS, DAYS, MONTHS
from python.temporal_hierarchy import  ForecastLevel,  TemporalHierarchy


th = TemporalHierarchy([DAYS, WEEKDAYS, WEEKS, MONTHS])
th.resample_time_series(X)
th.make_base_forecasts(28)

In [40]:
import python.forecast_reconciliation

importlib.reload(python.forecast_reconciliation)

In [43]:
from python.forecast_reconciliation import ForecastReconciliation

fr = ForecastReconciliation(th)
fr.reconcile()

array([[[713.0226   , 175.90063  , 177.47882  , ...,  23.625471 ,
          31.235552 ,  31.235552 ]],

       [[875.48425  , 218.21611  , 218.70305  , ...,  32.94391  ,
          27.367126 ,  27.367126 ]],

       [[134.82414  ,  33.29966  ,  33.599583 , ...,   5.6421375,
           2.9300225,   2.9300225]],

       ...,

       [[174.1015   ,  43.52542  ,  43.525375 , ...,   7.9119596,
           1.9827819,   1.9827819]],

       [[456.20395  , 114.05098  , 114.05098  , ...,  16.317144 ,
          16.23263  ,  16.23263  ]],

       [[673.22974  , 168.68579  , 168.43015  , ...,  15.451826 ,
          45.337517 ,  45.337517 ]]], shape=(93, 1, 37), dtype=float32)

In [ ]:
fr.get_agg_mat()

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 1, 1, 1, 0, 0]])

In [44]:
th.reorder_base_forecasts()[0]

array([[739.1406  , 157.37045 , 158.20435 , 159.02156 , 159.82243 ,
         97.24399 , 101.66842 , 106.09286 , 110.51729 ,  25.893553,
         25.893553,  25.893553,  25.893553,  25.893553,  25.893553,
         25.893553,  25.893553,  25.893553,  25.893553,  25.893553,
         25.893553,  25.893553,  25.893553,  25.893553,  25.893553,
         25.893553,  25.893553,  25.893553,  25.893553,  25.893553,
         25.893553,  25.893553,  25.893553,  25.893553,  25.893553,
         25.893553,  25.893553]], dtype=float32)

In [45]:
th.reorder_reconciled_forecasts()[0]

array([[713.0226  , 175.90063 , 177.47882 , 179.04468 , 180.59846 ,
        108.93783 , 112.00461 , 115.067764, 118.12737 ,  21.787563,
         21.787563,  21.787563,  21.787563,  21.787563,  33.4814  ,
         33.4814  ,  22.40092 ,  22.40092 ,  22.40092 ,  22.40092 ,
         22.40092 ,  32.737106,  32.737106,  23.01355 ,  23.01355 ,
         23.01355 ,  23.01355 ,  23.01355 ,  31.988459,  31.988459,
         23.625471,  23.625471,  23.625471,  23.625471,  23.625471,
         31.235552,  31.235552]], dtype=float32)

In [35]:
weeks = th.forecast_levels[1]
weeks.base_forecasts

,2NE1_zh.wikipedia.org_all-access_spider,2PM_zh.wikipedia.org_all-access_spider,3C_zh.wikipedia.org_all-access_spider,4minute_zh.wikipedia.org_all-access_spider,52_Hz_I_Love_You_zh.wikipedia.org_all-access_spider,5566_zh.wikipedia.org_all-access_spider,91Days_zh.wikipedia.org_all-access_spider,A'N'D_zh.wikipedia.org_all-access_spider,AKB48_zh.wikipedia.org_all-access_spider,ASCII_zh.wikipedia.org_all-access_spider,...,Lovelyz_zh.wikipedia.org_all-access_spider,Lulu_zh.wikipedia.org_all-access_spider,MADTOWN_zh.wikipedia.org_all-access_spider,MAMAMOO_zh.wikipedia.org_all-access_spider,MONSTA_X_zh.wikipedia.org_all-access_spider,Madame_Antoine_zh.wikipedia.org_all-access_spider,Mamamoo_zh.wikipedia.org_all-access_spider,Mike_D._Angelo_zh.wikipedia.org_all-access_spider,Miss_A_zh.wikipedia.org_all-access_spider,Missing9_zh.wikipedia.org_all-access_spider
ds,,,,,,,,,,,,,,,,,,,,,
2017-08-18,97.243988,170.271698,27.632576,63.628857,82.975868,97.658234,41.652454,200.848312,207.988022,146.788437,...,197.882767,18.30402,32.258152,48.063522,139.204468,19.827604,159.498169,45.488972,81.670235,50.831047
2017-08-25,101.668419,170.280502,28.926651,62.823971,88.843719,97.658234,44.033432,200.848312,207.988022,146.788437,...,209.823547,18.30402,32.258152,48.627529,138.571106,19.869701,159.498169,45.488972,81.670235,49.655151
2017-09-01,106.092857,170.288696,30.012192,62.019089,93.840866,97.658234,46.414410,200.848312,207.988022,146.788437,...,221.764343,18.30402,32.258152,49.191536,137.950424,19.906076,159.498169,45.488972,81.670235,48.502777
2017-09-08,110.517288,170.296310,30.922802,61.214207,98.096512,97.658234,48.795391,200.848312,207.988022,146.788437,...,233.705124,18.30402,32.258152,49.755539,137.342133,19.937508,159.498169,45.488972,81.670235,47.373451

In [36]:
weeks.reconciled_forecasts

,2NE1_zh.wikipedia.org_all-access_spider,2PM_zh.wikipedia.org_all-access_spider,3C_zh.wikipedia.org_all-access_spider,4minute_zh.wikipedia.org_all-access_spider,52_Hz_I_Love_You_zh.wikipedia.org_all-access_spider,5566_zh.wikipedia.org_all-access_spider,91Days_zh.wikipedia.org_all-access_spider,A'N'D_zh.wikipedia.org_all-access_spider,AKB48_zh.wikipedia.org_all-access_spider,ASCII_zh.wikipedia.org_all-access_spider,...,Lovelyz_zh.wikipedia.org_all-access_spider,Lulu_zh.wikipedia.org_all-access_spider,MADTOWN_zh.wikipedia.org_all-access_spider,MAMAMOO_zh.wikipedia.org_all-access_spider,MONSTA_X_zh.wikipedia.org_all-access_spider,Madame_Antoine_zh.wikipedia.org_all-access_spider,Mamamoo_zh.wikipedia.org_all-access_spider,Mike_D._Angelo_zh.wikipedia.org_all-access_spider,Miss_A_zh.wikipedia.org_all-access_spider,Missing9_zh.wikipedia.org_all-access_spider
ds,,,,,,,,,,,,,,,,,,,,,
2017-08-18,31.988459,27.248512,3.121416,21.309460,23.696077,17.474361,7.924394,64.074776,41.229401,24.680981,...,28.717257,3.451467,3.128015,9.728812,48.723137,2.757700,26.453739,1.982782,16.232630,45.092010
2017-08-25,31.988459,27.248512,3.121416,21.309460,23.696077,17.474369,7.924394,66.239380,41.344105,24.680981,...,29.249571,3.451467,3.128015,9.728812,48.698524,2.757700,26.453739,1.982781,16.232630,45.092010
2017-09-01,23.625471,32.943909,5.642138,13.736904,20.144577,19.188757,9.438190,39.401131,40.927376,28.578236,...,42.591206,3.625915,5.897696,9.911819,30.986376,3.778956,30.991985,7.911961,16.317144,15.451826
2017-09-08,23.625471,32.943909,5.642138,13.736904,20.144577,19.188763,9.438190,41.565735,41.042076,28.578236,...,43.123524,3.625915,5.897696,9.911819,30.962736,3.778956,30.991985,7.911961,16.317144,15.451826