In [23]:
import utils
import importlib

importlib.reload(utils)

X = utils.fetch_dataset_web_traffic('wide')

In [25]:
X.isna().describe()

,ds,2NE1_zh.wikipedia.org_all-access_spider,2PM_zh.wikipedia.org_all-access_spider,3C_zh.wikipedia.org_all-access_spider,4minute_zh.wikipedia.org_all-access_spider,52_Hz_I_Love_You_zh.wikipedia.org_all-access_spider,5566_zh.wikipedia.org_all-access_spider,91Days_zh.wikipedia.org_all-access_spider,A'N'D_zh.wikipedia.org_all-access_spider,AKB48_zh.wikipedia.org_all-access_spider,...,Drake_(músico)_es.wikipedia.org_all-access_spider,Skam_(serie_de_televisión)_es.wikipedia.org_all-access_spider,Legión_(serie_de_televisión)_es.wikipedia.org_all-access_spider,Doble_tentación_es.wikipedia.org_all-access_spider,Mi_adorable_maldición_es.wikipedia.org_all-access_spider,Underworld_(serie_de_películas)_es.wikipedia.org_all-access_spider,Resident_Evil:_Capítulo_Final_es.wikipedia.org_all-access_spider,Enamorándome_de_Ramón_es.wikipedia.org_all-access_spider,Hasta_el_último_hombre_es.wikipedia.org_all-access_spider,Francisco_el_matemático_(serie_de_televisión_de_2017)_es.wikipedia.org_all-access_spider
count,803,803,803,803,803,803,803,803,803,803,...,803,803,803,803,803,803,803,803,803,803
unique,1,1,1,1,1,2,1,2,1,1,...,2,2,2,2,2,2,2,2,2,2
top,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
freq,803,803,803,803,803,512,803,438,803,803,...,496,515,525,546,560,544,564,579,573,585

In [30]:
X.tail(20)

,ds,2NE1_zh.wikipedia.org_all-access_spider,2PM_zh.wikipedia.org_all-access_spider,3C_zh.wikipedia.org_all-access_spider,4minute_zh.wikipedia.org_all-access_spider,52_Hz_I_Love_You_zh.wikipedia.org_all-access_spider,5566_zh.wikipedia.org_all-access_spider,91Days_zh.wikipedia.org_all-access_spider,A'N'D_zh.wikipedia.org_all-access_spider,AKB48_zh.wikipedia.org_all-access_spider,...,Drake_(músico)_es.wikipedia.org_all-access_spider,Skam_(serie_de_televisión)_es.wikipedia.org_all-access_spider,Legión_(serie_de_televisión)_es.wikipedia.org_all-access_spider,Doble_tentación_es.wikipedia.org_all-access_spider,Mi_adorable_maldición_es.wikipedia.org_all-access_spider,Underworld_(serie_de_películas)_es.wikipedia.org_all-access_spider,Resident_Evil:_Capítulo_Final_es.wikipedia.org_all-access_spider,Enamorándome_de_Ramón_es.wikipedia.org_all-access_spider,Hasta_el_último_hombre_es.wikipedia.org_all-access_spider,Francisco_el_matemático_(serie_de_televisión_de_2017)_es.wikipedia.org_all-access_spider
783,2017-08-22,37.0,14.0,6.0,21.0,23.0,32.0,9.0,175.0,35.0,...,1.0,3.0,1.0,4.0,5.0,2.0,9.0,9.0,1.0,1.0
784,2017-08-23,58.0,34.0,23.0,42.0,41.0,46.0,68.0,84.0,60.0,...,4.0,13.0,8.0,10.0,8.0,7.0,10.0,16.0,10.0,9.0
785,2017-08-24,25.0,16.0,11.0,23.0,25.0,31.0,8.0,32.0,36.0,...,62.0,19.0,7.0,14.0,10.0,6.0,8.0,10.0,10.0,5.0
786,2017-08-25,23.0,31.0,8.0,17.0,22.0,29.0,40.0,37.0,32.0,...,6.0,9.0,5.0,23.0,10.0,8.0,6.0,12.0,11.0,8.0
787,2017-08-26,25.0,34.0,6.0,11.0,20.0,31.0,6.0,105.0,30.0,...,5.0,7.0,2.0,9.0,10.0,5.0,3.0,10.0,3.0,5.0
788,2017-08-27,47.0,33.0,13.0,21.0,24.0,28.0,14.0,52.0,41.0,...,5.0,8.0,8.0,19.0,7.0,7.0,9.0,13.0,10.0,8.0
789,2017-08-28,44.0,32.0,12.0,20.0,29.0,17.0,11.0,72.0,31.0,...,4.0,11.0,1.0,4.0,7.0,7.0,2.0,10.0,5.0,11.0
790,2017-08-29,26.0,29.0,8.0,20.0,20.0,16.0,6.0,25.0,29.0,...,6.0,10.0,5.0,12.0,10.0,7.0,11.0,21.0,3.0,9.0
791,2017-08-30,24.0,34.0,12.0,110.0,17.0,8.0,9.0,86.0,68.0,...,5.0,10.0,6.0,19.0,6.0,8.0,3.0,11.0,9.0,6.0
792,2017-08-31,21.0,25.0,9.0,15.0,24.0,13.0,7.0,52.0,40.0,...,1.0,13.0,3.0,21.0,10.0,2.0,3.0,9.0,2.0,5.0
793,2017-09-01,19.0,32.0,6.0,7.0,16.0,13.0,12.0,74.0,53.0,...,1.0,4.0,3.0,9.0,5.0,0.0,4.0,11.0,4.0,2.0
794,2017-09-02,33.0,30.0,6.0,19.0,16.0,13.0,8.0,39.0,107.0,...,3.0,10.0,1.0,51.0,5.0,4.0,4.0,25.0,6.0,29.0
795,2017-09-03,33.0,11.0,7.0,19.0,19.0,45.0,5.0,11.0,63.0,...,1.0,8.0,4.0,13.0,11.0,3.0,7.0,22.0,5.0,6.0
796,2017-09-04,18.0,19.0,2.0,9.0,9.0,4.0,7.0,55.0,42.0,...,3.0,5.0,2.0,6.0,6.0,6.0,5.0,47.0,1.0,5.0
797,2017-09-05,16.0,54.0,4.0,6.0,20.0,13.0,8.0,71.0,24.0,...,2.0,5.0,1.0,25.0,9.0,5.0,0.0,42.0,5.0,2.0
798,2017-09-06,27.0,25.0,7.0,16.0,23.0,20.0,10.0,44.0,44.0,...,2.0,4.0,5.0,19.0,8.0,2.0,5.0,13.0,8.0,2.0
799,2017-09-07,29.0,26.0,3.0,19.0,28.0,18.0,8.0,25.0,33.0,...,0.0,8.0,3.0,7.0,7.0,4.0,5.0,9.0,2.0,7.0
800,2017-09-08,23.0,23.0,4.0,30.0,14.0,17.0,5.0,39.0,52.0,...,5.0,7.0,4.0,14.0,9.0,4.0,2.0,21.0,4.0,6.0
801,2017-09-09,54.0,13.0,7.0,38.0,8.0,14.0,3.0,25.0,21.0,...,7.0,7.0,3.0,12.0,11.0,8.0,2.0,16.0,3.0,10.0
802,2017-09-10,38.0,81.0,6.0,4.0,7.0,11.0,5.0,50.0,48.0,...,1.0,19.0,3.0,8.0,5.0,2.0,4.0,6.0,3.0,3.0